# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: helloworld.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class GreeterServer(TwirpServer):

	def __init__(self, *args, service):
		super().__init__(service=service)
		self._prefix = "/twirp/apis.Greeter"
		self._endpoints = {
			"sayHello": Endpoint(
				service_name="Greeter",
				name="sayHello",
				function=getattr(service, "sayHello"),
				input=_sym_db.GetSymbol("apis.HelloRequest"),
				output=_sym_db.GetSymbol("apis.HelloReply"),
			),
		}

class GreeterClient(TwirpClient):

	def sayHello(self, *args, ctx, request, **kwargs):
		return self._make_request(
			url="/twirp/apis.Greeter/sayHello",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("apis.HelloReply"),
			**kwargs,
		)
