[package]
name = "apis"
version = "0.1.0"
authors = ["Ken Sato <ksato9700@gmail.com>"]
edition = "2018"
build = "build.rs"

#[lib]
#name = "apis"
#path = "src/lib.rs"

[dependencies]
futures = "0.3.5"
grpcio = "0.6.0"
protobuf = "~2"

[build-dependencies]
protoc-grpcio = "2.0.0"

